title: Golden Slumber
email: rfg1024@outlook.com
description: The blog name is from one of my favourite novels.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rfg1024.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  rfg1024
google_analytics: G-MNN0BVYLX1
# google_analytics: UA-263002412-1
# Build settings
highlighter-theme: monokai
date_format: "%Y-%M-%D"
plugins:
  - jekyll-feed
category_dir: category/
tag_dir: tag/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - public/*.md
  - public/*/*.md